class Data:
    def returnmap():
        return dict( {'Addis Ababa': {'Adama', 'Ambo', 'Debre Berhan'},
             'Adama': {'Matahara', 'Asella', 'Batu', 'Addis Ababa'}, 
             'Ambo': {'Wolkite', 'Addis Ababa', 'Nekemte'}, 
             'Debre Berhan': {'Addis Ababa', 'Debre Sina'}, 
             'Matahara': {'Adama', 'Awash'}, 
             'Asella': {'Adama', 'Assasa'}, 
             'Batu': {'Adama', 'Buta Jirra', 'Shashamene'}, 
             'Wolkite': {'Ambo', 'Worabe', 'Jimma'}, 
             'Nekemte': {'Ambo', 'Bedelle', 'Gimbi'}, 
             'Debre Sina': {'Debre Berhan', 'Kemise', 'Debre Markos'}, 
             'Awash': {'Chiro', 'Gobi Rasu', 'Matahara'}, 
             'Assasa': {'Asella', 'Dodolla'}, 
             'Buta Jirra': {'Batu', 'Worabe'}, 
             'Shashamene': {'Batu', 'Hawassa', 'Dodolla', 'Hossana'}, 
             'Worabe': {'Wolkite', 'Hossana', 'Buta Jirra'}, 
             'Jimma': {'Wolkite', 'Bonga', 'Bedelle'}, 
            'Bedelle': {'Nekemte', 'Gore', 'Jimma'}, 
             'Gimbi': {'Nekemte', 'Dambidollo'}, 
             'Kemise': {'Debre Sina', 'Dessie'}, 
             'Debre Markos': {'Debre Sina', 'Finote Selam'},
             'Chiro': {'Awash', 'Dire Dawa'}, 
             'Gobi Rasu': {'Awash', 'Samara'}, 
             'Dodolla': {'Assasa', 'Shashamene', 'Bale'}, 
             'Hawassa': {'Shashamene', 'Dilla'}, 
             'Hossana': {'Shashamene', 'Worabe', 'Wolaita Sodo'}, 
             'Bonga': {'Jimma', 'Dawro', 'Tepi', 'Mizan Teferi'}, 
             'Gore': {'Tepi', 'Gambella', 'Bedelle'}, 
             'Dambidollo': {'Gimbi', 'Assosa', 'Gambella'}, 
            'Dessie': {'Kemise', 'Woldia'}, 
            'Finote Selam': {'Debre Markos', 'Bahirdar', 'Injibara'}, 
             'Dire Dawa': { 'Chiro', 'Harar'}, 
             'Samara': { 'Gobi Rasu', 'Fanti Rasu', 'Alamata', 'Woldia'},
            'Bale': {'Liben', 'Dodolla', 'Goba', 'Sof Oumer'}, 
             'Dilla': {'Hawassa', 'Bulehora'}, 
             'Wolaita Sodo': {'Arba Minchi', 'Dawro', 'Hossana'}, 
             'Dawro': { 'Bonga', 'Basketo', 'Wolaita Sodo'}, 
             'Tepi': {'Gore', 'Bonga', 'Mizan Teferi'}, 
            'Mizan Teferi': {'Tepi', 'Bonga', 'Basketo'}, 
             'Gambella': {'Gore', 'Dambidollo'}, 
             'Assosa': {'Dambidollo', 'Metekel'}, 
            'Woldia': {'Dessie', 'Lalibella', 'Samara', 'Alamata'},
             'Bahirdar': {'Finote Selam', 'Injibara', 'Metekel', 'Azezo', 'Debre Tabor'}, 
             'Injibara': {'Bahirdar', 'Finote Selam'}, 
             'Harar': { 'Dire Dawa', 'Babile'}, 
             'Fanti Rasu': {'Samara', 'Kilbet Rasu'}, 
             'Alamata': {'Samara', 'Woldia', 'Mekelle', 'Sekota'}, 
             'Liben': {'Bale'}, 
             'Goba': {'Bale', 'Sof Oumer', 'Dega Habur'}, 
             'Sof Oumer': {'Goba', 'Bale', 'Kebri Dehar'}, 
            'Bulehora': { 'Dilla', 'Yabello'}, 
            'Arba Minchi': {'Wolaita Sodo', 'Konso', 'Basketo'}, 
             'Basketo': { 'Arba Minchi', 'Dawro', 'Mizan Teferi', 'Benchi Maji'}, 
             'Metekel': { 'Assosa', 'Bahirdar'},
             'Lalibella': {'Woldia', 'Debre Tabor', 'Sekota'},
             'Debre Tabor': {'Lalibella', 'Bahirdar'}, 
             'Azezo': {'Gondar', 'Bahirdar', 'Metema'}, 
             'Babile': { 'Harar', 'Jigjiga'}, 
             'Kilbet Rasu': {'Fanti Rasu' }, 
             'Mekelle': {'Alamata', 'Adwa', 'Adigrat', 'Sekota'}, 
             'Sekota': {'Alamata', 'Mekelle', 'Lalibella'}, 
            'Dega Habur': {'Goba', 'Jigjiga', 'Kebri Dehar'}, 
            'Kebri Dehar': {'Gode', 'Sof Oumer', 'Dega Habur', 'Werdez'}, 
            'Yabello': { 'Bulehora', 'Konso', 'Moyale'}, 
            'Konso': {'Arba Minchi', 'Yabello'}, 
            'Benchi Maji': { 'Basketo'}, 
            'Gondar': { 'Azezo', 'Metema', 'Debarke'},
            'Metema': { 'Azezo', 'Gondar'},  
            'Jigjiga': { 'Babile', 'Dega Habur'}, 
            'Adwa': { 'Mekelle', 'Axum', 'Adigrat'},
            'Adigrat': { 'Mekelle', 'Adwa'}, 
            'Gode': { 'Dollo', 'Kebri Dehar' }, 
            'Werdez': { 'Kebri Dehar'}, 
            'Moyale': { 'Yabello'}, 
            'Debarke': { 'Gondar', 'Shire'}, 
            'Axum': {'Shire', 'Adwa'}, 
            'Dollo': { 'Gode'}, 
            'Shire': { 'Axum', 'Humera', 'Debarke'},
            'Humera': { 'Shire', 'Gondar'}})