class mapclass:
    def return_map():
        return dict( {
                        'Kebri Dehar': { 'Dega Habur':6, 'Gode':5, 'Werdez':6}, 
             'Debre Tabor': {'Lalibella':8, 'Gondar':6, 'Bahirdar':4},
             'Adama': {'Matahara':3, 'Addis Ababa':3, 'Asella':4, 'Batu':4}, 
             'Adwa': { 'Mekelle':7, 'Axum':1, 'Adigrat':4},
             'Sekota': {'Alamata':6, 'Mekelle':9, 'Lalibella':6}, 
             'Wolaita Sodo': { 'Hossana':4,'Arba Minchi':4, 'Dawro':6}, 
            'Awash': {'Chiro':4,  'Matahara':1,'Gobi Rasu':5,}, 
             'Dodolla': {'Assasa':1, 'Shashamene':3, 'Robe':13}, 
             'Nekemte': {'Ambo':9, 'Bedelle':5, 'Gimbi':4}, 
             'Batu': {'Adama':4, 'Buta Jirra':2, 'Shashamene':3}, 
             'Dawro': { 'Bonga':10, 'Wolaita Sodo':6}, 
             'Dessie': {'Kemise':4, 'Woldia':6},
             'Lalibella': {'Woldia':7, 'Debre Tabor':8, 'Sekota':6},
             'Tepi': {'Gore':9, 'Bonga':8, 'Mizan Teferi':4}, 
             'Gobi Rasu': {'Awash':5, 'Samara':10}, 
             'Dollo':{'Gode':17,'Moyale':18},
             'Debre Markos':{'Addis Ababa':13,'Debre Sina':17,'Finote Selam':3},                  
             'Babile': { 'Harar':2, 'Jigjiga':3,'Goba':28}, 
             'Fanti Rasu': {'Samara':7, 'Kilbet Rasu':6}, 
             'Debre Sina': {'Debre Berhan':2, 'Kemise':7, 'Debre Markos':17}, 
             'Yabello': { 'Bulehora':3, 'Konso':3, 'Moyale':6},
             'Ambo': {'Wolkite':6, 'Addis Ababa':5, 'Nekemte':8}, 
             'Sof Oumer': {'Goba':6, 'Robe':23, 'Gode':23}, 
             'Humera': { 'Shire':8, 'Gondar':9},
             'Hawassa': {'Shashamene':1, 'Dilla':3}, 
             'Mekelle': {'Alamata':5, 'Adigrat':4, 'Adwa':7, 'Sekota':9},
             'Kilbet Rasu': {'Fanti Rasu':6}, 
             'Adigrat': { 'Mekelle':4, 'Adwa':4},
             'Metekel': { 'Bahirdar':11},
             'Gondar': { 'Azezo':1, 'Humera':9, 'Metema':7, 'Debarke':4,'Debre Tabor':6},
             'Jimma': {'Wolkite':8, 'Bonga':4, 'Bedelle':7}, 
             'Injibara': {'Bahirdar':4, 'Finote Selam':2},            
             'Bulehora': { 'Dilla':4, 'Yabello':3}, 
             'Shire': { 'Axum':2, 'Humera':8, 'Debarke':7},
             'Gimbi': {'Nekemte':4, 'Dambidollo':6,'Assosa':8}, 
             'Dire Dawa': { 'Chiro':8, 'Harar':4}, 
             'Shashamene': {'Batu':3,'Dodolla':3, 'Hawassa':1, 'Hossana':7,'Worabe':6}, 
             'Assosa': {'Gimbi':8, 'Dambidollo':12}, 
             'Bahirdar': {'Finote Selam':6, 'Injibara':4, 'Metekel':11, 'Azezo':7, 'Debre Tabor':4},
             'Mizan Teferi': {'Tepi':4, 'Bonga':4}, 
             'Arba Minchi': {'Wolaita Sodo':5, 'Konso':4, 'Basketo':10},
             'Harar': { 'Dire Dawa':4, 'Babile':2}, 
             'Hossana': {'Shashamene':7, 'Worabe':2, 'Wolkite':5, 'Wolaita Sodo':4}, 
             'Gore': {'Tepi':9, 'Gambella':5, 'Bedelle':6}, 
             'Dambidollo': {'Gimbi':6, 'Assosa':12, 'Gambella':4}, 
            'Addis Ababa': {'Adama':3, 'Ambo':5, 'Debre Berhan':5,'Debre Markos':13},
             'Matahara': {'Adama':3, 'Awash':1}, 
             'Goba': {'Robe':18, 'Sof Oumer':6, 'Babile':28}, 
             'Worabe': {'Wolkite':5, 'Hossana':2,'Shashamene':6, 'Buta Jirra':2}, 
             'Samara': { 'Gobi Rasu':10, 'Fanti Rasu':7, 'Alamata':11, 'Woldia':8},
             'Woldia': {'Dessie':6, 'Lalibella':7, 'Samara':8, 'Alamata':3},
             'Bench Maji': { 'Basketo':5}, 
             'Chiro': {'Awash':4, 'Dire Dawa':8}, 
             'Assasa': {'Asella':4, 'Dodolla':1}, 
             'Dega Habur': {'Jigjiga':5, 'Kebri Dehar':6}, 
             'Asella': {'Adama':4, 'Assasa':4}, 
             'Gode': { 'Dollo':17, 'Kebri Dehar':5, 'Sof Oumer':23 }, 
             'Gambella': {'Gore':5, 'Dambidollo':4}, 
             'Alamata': {'Samara':11, 'Woldia':3, 'Mekelle':5, 'Sekota':6}, 
             'Bonga': {'Jimma':4, 'Dawro':10, 'Tepi':8, 'Mizan Teferi':4}, 
             'Werdez': { 'Kebri Dehar':6}     ,
            'Finote Selam': {'Debre Markos':3, 'Bahirdar':6, 'Injibara':2},
             'Moyale': { 'Dollo':18,'Liben':11,'Yabello':6}, 
             'Liben': {'Robe':11}, 
             'Konso': {'Arba Minchi':4, 'Yabello':3}, 
             'Metema': { 'Azezo':7, 'Gondar':7}, 
             'Basketo': { 'Arba Minchi':10, 'Bench Maji':5}, 
             'Bedelle': {'Nekemte':5, 'Gore':6, 'Jimma':7}, 
             'Debarke': { 'Shire':7 , 'Gondar':4 },
             'Axum': {'Shire':2, 'Adwa':1},
             'Dilla': { 'Bulehora':4,'Hawassa':3}, 
             'Debre Berhan': {'Addis Ababa':5, 'Debre Sina':2},
             'Jigjiga': { 'Babile':3, 'Dega Habur':5}, 
             'Buta Jirra': {'Wolkite':4, 'Batu':2, 'Worabe':2}, 
             'Wolkite': {'Worabe':5, 'Jimma':8,'Buta Jirra':4,'Ambo':6, 'Hossana':5,}, 
             'Azezo': { 'Bahirdar':7,'Gondar':1, 'Metema':7}, 
             'Robe': {'Liben':11, 'Dodolla':13, 'Goba':18, 'Sof Oumer':23}, 
             'Kemise': {'Dessie':4,'Debre Sina':6 }, 

        
    }
)